_base_: exp_acds_full_fast.yaml

output_dir: outputs/exp_acds_full_fast_r18

model:
  backbone: resnet18
  num_queries: 150
  enc_layers: 1
  dec_layers: 3
  dim_feedforward: 512

loss:
  aux_loss_layers: 1

